# -*- mode: python ; coding: utf-8 -*-
import glob as _glob
import os as _os

block_cipher = None

# llama-cpp-python loads its native engine (llama.dll, ggml-*.dll, mtmd.dll)
# via ctypes from <package>/lib at runtime. PyInstaller's dependency scan
# cannot see ctypes loads, so collect the DLLs explicitly. Without these the
# frozen backend imports llama_cpp fine but Llama() construction fails.
_llama_binaries: list[tuple[str, str]] = []
try:
    import llama_cpp as _lc

    _lc_lib = _os.path.join(_os.path.dirname(_lc.__file__), "lib")
    for _dll in sorted(_glob.glob(_os.path.join(_lc_lib, "*.dll"))):
        _llama_binaries.append((_dll, "llama_cpp/lib"))
except Exception:
    pass

a = Analysis(
    ['run_backend.py'],
    pathex=[r'C:\Users\Aryan Sonsurkar\OneDrive\Documents\GitHub\Fixly-Desktop\apps\backend'],
    binaries=_llama_binaries,
    datas=[],
    hiddenimports=[
        'pypdf',
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.asymmetric',
        'cryptography.hazmat.primitives.asymmetric.ec',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        'app.main',
        'app.config',
        'app.core.exceptions',
        'app.core.feature_flags',
        'app.core.jwt',
        'app.core.logging',
        'app.core.supabase',
        'app.core.threads',
        'app.dependencies.auth',
        'app.prompts.manager',
        'app.prompts.registry',
        'app.prompts.utils',
        'app.prompts.templates.assignment',
        'app.prompts.templates.briefing',
        'app.prompts.templates.coding',
        'app.prompts.templates.daily_mission',
        'app.prompts.templates.email',
        'app.prompts.templates.insights',
        'app.prompts.templates.ocr',
        'app.prompts.templates.pdf',
        'app.prompts.templates.planner',
        'app.prompts.templates.productivity_coach',
        'app.prompts.templates.rescheduler',
        'app.prompts.templates.risk_detector',
        'app.prompts.templates.screenshot',
        'app.prompts.templates.smart_commands',
        'app.prompts.templates.study',
        'app.prompts.templates.summary',
        'app.prompts.templates.system',
        'app.prompts.templates.weekly_review',
        'app.repositories.ai_repository',
        'app.repositories.assignment_repository',
        'app.repositories.auth_repository',
        'app.repositories.document_repository',
        'app.repositories.email_repository',
        'app.repositories.notification_repository',
        'app.repositories.pomodoro_repository',
        'app.repositories.profile_repository',
        'app.repositories.study_repository',
        'app.repositories.subject_repository',
        'app.schemas.ai',
        'app.schemas.assignment',
        'app.schemas.auth',
        'app.schemas.copilot',
        'app.schemas.document',
        'app.schemas.email',
        'app.schemas.notification',
        'app.schemas.planner',
        'app.schemas.pomodoro',
        'app.schemas.profile',
        'app.schemas.search',
        'app.schemas.study',
        'app.schemas.subject',
        'app.services.ai_service',
        'app.services.assignment_service',
        'app.services.auth_service',
        'app.services.command_service',
        'app.services.context_service',
        'app.services.copilot_service',
        'app.services.dashboard_service',
        'app.services.document_service',
        'app.services.email_service',
        'app.services.insight_service',
        'app.services.notification_service',
        'app.services.ocr_service',
        'app.services.pdf_service',
        'app.services.planner_service',
        'app.services.pomodoro_service',
        'app.services.profile_service',
        'app.services.risk_detector_service',
        'app.services.search_service',
        'app.services.study_scoring',
        'app.services.study_service',
        'app.services.subject_service',
        'app.services.token_counter',
        'app.services.workspace_context',
        'app.services.embedding_service',
        'app.services.vector_store',
        'app.services.rag_service',
        'app.providers.base',
                'app.providers.gmail',
        'app.providers.imap',
                'app.providers.fixly_local',
        # Bundled local AI runtime (native GGUF engine) — must ship in the frozen exe
        'llama_cpp',
        'llama_cpp.llama_cpp',
        'llama_cpp.llama',
        'llama_cpp._internals',
        'diskcache',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'scipy', 'PIL', 'cv2',
        'tensorflow', 'spacy', 'thinc',
        'boto3', 'botocore', 'flask', 'django', 'sqlalchemy', 'alembic',
        'pytest', 'mypy', 'ruff', 'setuptools', 'pip', 'wheel',
        'playwright', 'sounddevice', 'soundfile', 'faster_whisper',
        'moviepy', 'pillow', 'ImageIO', 'gtts', 'edge_tts', 'kokoro',
        'phonemizer_fork', 'playsound', 'onnxruntime',
        'tokenizers', 'joblib', 'sympy',
        'pygments', 'rich', 'apscheduler', 'psutil', 'tenacity',
        'addict', 'av', 'babel', 'bottle', 'cloudpathlib', 'clr_loader',
        'csvw', 'ctranslate2', 'curated_tokenizers', 'curated_transformers',
        'dbgpu', 'decorator', 'defusedxml', 'dlinfo', 'docopt',
        'en_core_web_sm', 'espeakng_loader', 'filelock', 'flatbuffers',
        'fonttools', 'fpdf2', 'fsspec', 'greenlet', 'hf_xet',
        'huggingface_hub', 'imageio_ffmpeg', 'isodate',
        'jsonschema', 'jsonschema_specifications', 'language_tags',
        'loguru', 'misaki', 'mpmath', 'networkx', 'num2words',
        'nvidia_ml_py', 'pefile', 'phonemizer_fork', 'playwright',
        'proglog', 'protobuf', 'proxy_tools', 'pycparser',
        'pyee', 'pyinstaller', 'pyinstaller_hooks_contrib',
        'pywin32_ctypes', 'pyyaml', 'rapidfuzz', 'rdflib', 'referencing',
        'requests', 'rfc3986', 'rpds_py', 'shellingham', 'six',
        'smart_open', 'spacy_curated_transformers', 'spacy_legacy',
        'spacy_loggers', 'srsly', 'tabulate', 'termcolor',
        'thefuzz', 'tqdm', 'typer', 'tzdata', 'tzlocal', 'uritemplate',
        'wasabi', 'weasel', 'whichllm', 'win32_setctime', 'wrapt',
        'pywebview', 'pythonnet', 'playsound',
    ],
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
